version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "80:8080" # 외부 포트를 80번으로 매핑
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    ports:
      - "8085:8085"
    networks:
      - app-network

  db:
    container_name: mysql-moyeomoyeo
    image: mysql:8.0.31
    ports:
      - "3333:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moyeomoyeo
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d

networks:
  app-network:
    driver: bridge
